### ISSUE TITLE
Update tubetool and sharetool to use new teleport tube API

### ISSUE THREAD

**Issue by OgelGames** [S-S-X/metatool#124]
Reported on Pandorabox:
> \<Huhhila\> Tubetool regression: No longer sets receive on/off state, only the channel.

Due to how the tube tool sets the channel and receiving state by calling `on_receive_fields`, the setting of the receive state was broken by the recent teleport tube update that changed the field names in the formspec.

I think instead of reverting the name change in teleport tubes, it would be better to update the tools to use the new API:

- `pipeworks.tptube.update_tube(pos, channel, can_receive, player_name)` - Checks channel and owner before setting.
- `pipeworks.tptube.set_tube(pos, channel, can_receive)` - Directly sets the channel and receiving state. (this gets called by `update_tube`)

**Comment by S-S-X** [comment]
Somehow this has gone completely unnoticed for me, just happened to come check what stuff there was open and found this.
And yes sure should update to use actual API, on_receive_fields was picked first only because there wasn't any API at all.

Seems I've actually even replied something to another message that apparently was about exact same issue:

> Kinda wishing for a tubetool fix, currently it sets only tptube-channel, failing to set sending/receiving mode. Or does digiline interface exist for allowing/disabling receive?

I guess it is still broken, going to take a look at it soon.
